// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountMe(arg1) {
  return window['go']['main']['App']['AccountMe'](arg1);
}

export function AccountSubscriptions(arg1) {
  return window['go']['main']['App']['AccountSubscriptions'](arg1);
}

export function ApiRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApiRequest'](arg1, arg2, arg3, arg4);
}

export function ApiRequestBlob(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApiRequestBlob'](arg1, arg2, arg3);
}

export function CheckAccountAndSave(arg1) {
  return window['go']['main']['App']['CheckAccountAndSave'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearVideoDownloads() {
  return window['go']['main']['App']['ClearVideoDownloads']();
}

export function CreateVideo(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateVideo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteTaskData(arg1, arg2) {
  return window['go']['main']['App']['DeleteTaskData'](arg1, arg2);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function FetchDrafts(arg1, arg2) {
  return window['go']['main']['App']['FetchDrafts'](arg1, arg2);
}

export function GetBaseURL() {
  return window['go']['main']['App']['GetBaseURL']();
}

export function GetBearerByTokenID(arg1) {
  return window['go']['main']['App']['GetBearerByTokenID'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetIncompleteVideoTasks() {
  return window['go']['main']['App']['GetIncompleteVideoTasks']();
}

export function GetLocalFileDataURL(arg1) {
  return window['go']['main']['App']['GetLocalFileDataURL'](arg1);
}

export function GetLocalFileURL(arg1) {
  return window['go']['main']['App']['GetLocalFileURL'](arg1);
}

export function GetRandomVideoToken(arg1) {
  return window['go']['main']['App']['GetRandomVideoToken'](arg1);
}

export function GetTaskList() {
  return window['go']['main']['App']['GetTaskList']();
}

export function GetTokenEmailByID(arg1) {
  return window['go']['main']['App']['GetTokenEmailByID'](arg1);
}

export function GetTokenIDByRemoteTaskID(arg1) {
  return window['go']['main']['App']['GetTokenIDByRemoteTaskID'](arg1);
}

export function GetVideoDownloadsMap() {
  return window['go']['main']['App']['GetVideoDownloadsMap']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function LogDebug(arg1) {
  return window['go']['main']['App']['LogDebug'](arg1);
}

export function PollPending(arg1, arg2) {
  return window['go']['main']['App']['PollPending'](arg1, arg2);
}

export function PublishAndDownloadNoWatermark(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishAndDownloadNoWatermark'](arg1, arg2, arg3, arg4);
}

export function ReDownloadVideo(arg1) {
  return window['go']['main']['App']['ReDownloadVideo'](arg1);
}

export function SaveDraftsAndDownload(arg1, arg2) {
  return window['go']['main']['App']['SaveDraftsAndDownload'](arg1, arg2);
}

export function SaveVideoTaskResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveVideoTaskResult'](arg1, arg2, arg3);
}

export function SetBaseURL(arg1) {
  return window['go']['main']['App']['SetBaseURL'](arg1);
}

export function SetTaskList(arg1) {
  return window['go']['main']['App']['SetTaskList'](arg1);
}

export function SetTokenError(arg1, arg2) {
  return window['go']['main']['App']['SetTokenError'](arg1, arg2);
}

export function TestServerHealth(arg1) {
  return window['go']['main']['App']['TestServerHealth'](arg1);
}

export function UpdateVideoTaskProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateVideoTaskProgress'](arg1, arg2);
}
