// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AccountMe(arg1:string):Promise<string>;

export function AccountSubscriptions(arg1:string):Promise<string>;

export function ApiRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ApiRequestBlob(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckAccountAndSave(arg1:string):Promise<string>;

export function CheckForUpdates():Promise<string>;

export function ClearVideoDownloads():Promise<string>;

export function CreateVideo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function DeleteTaskData(arg1:string,arg2:boolean):Promise<string>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function FetchDrafts(arg1:string,arg2:string):Promise<string>;

export function GetBaseURL():Promise<string>;

export function GetBearerByTokenID(arg1:number):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function GetIncompleteVideoTasks():Promise<string>;

export function GetLocalFileDataURL(arg1:string):Promise<string>;

export function GetLocalFileURL(arg1:string):Promise<string>;

export function GetRandomVideoToken(arg1:boolean):Promise<string>;

export function GetTaskList():Promise<string>;

export function GetTokenEmailByID(arg1:number):Promise<string>;

export function GetTokenIDByRemoteTaskID(arg1:string):Promise<string>;

export function GetVideoDownloadsMap():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallUpdate(arg1:string):Promise<string>;

export function LogDebug(arg1:string):Promise<void>;

export function PollPending(arg1:string,arg2:string):Promise<string>;

export function PublishAndDownloadNoWatermark(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ReDownloadVideo(arg1:string):Promise<string>;

export function SaveDraftsAndDownload(arg1:string,arg2:string):Promise<string>;

export function SaveVideoTaskResult(arg1:number,arg2:string,arg3:string):Promise<string>;

export function SetBaseURL(arg1:string):Promise<void>;

export function SetTaskList(arg1:string):Promise<string>;

export function SetTokenError(arg1:number,arg2:string):Promise<string>;

export function TestServerHealth(arg1:string):Promise<main.HealthResult>;

export function UpdateVideoTaskProgress(arg1:string,arg2:number):Promise<string>;
